### ISSUE TITLE
Fail Testing Mosek 8 ->  ERROR: LoadError: ReadOnlyMemoryError()

### ISSUE THREAD

**Issue by erikfilias** [JuliaOpt/Mosek.jl#144] opened 2018-02-07 02:13 UTC
Testing Mosek on Windows with Julia v0.6.2, I could get:

@blegat
```julia
ERROR: LoadError: ReadOnlyMemoryError()
Stacktrace:
 [1] (::Mosek.##375#376{Mosek.Task,Int32,Int32,Array{Int64,1},Array{Float64,1},Int32})() at C:\Users\Erik\.julia\v0.6\Mosek\src\msk_functions.jl:5623
 [2] disable_sigint at .\c.jl:340 [inlined]
 [3] putbaraij(::Mosek.Task, ::Int32, ::Int32, ::Array{Int64,1}, ::Array{Float64,1}) at C:\Users\Erik\.julia\v0.6\Mosek\src\msk_functions.jl:5622
 [4] loadproblem!(::Mosek.MosekMathProgSolverInterface.MosekMathProgConicModel, ::Array{Float64,1}, ::SparseMatrixCSC{Float64,Int32}, ::Array{Float64,1}, ::Array{Tuple{Symbol,Any},1}, ::Array{Tuple{Symbol,Any},1}, ::Symbol) at C:\Users\Erik\.julia\v0.6\Mosek\src\MosekConicInterface.jl:278
 [5] loadproblem!(::Mosek.MosekMathProgSolverInterface.MosekMathProgConicModel, ::Array{Float64,1}, ::SparseMatrixCSC{Float64,Int32}, ::Array{Float64,1}, ::Array{Any,1}, ::Array{Any,1}, ::Symbol) at C:\Users\Erik\.julia\v0.6\Mosek\src\MosekConicInterface.jl:99
 [6] loadproblem!(::Mosek.MosekMathProgSolverInterface.MosekMathProgConicModel, ::Array{Float64,1}, ::SparseMatrixCSC{Float64,Int32}, ::Array{Float64,1}, ::Array{Any,1}, ::Array{Any,1}) at C:\Users\Erik\.julia\v0.6\Mosek\src\MosekConicInterface.jl:88
 [7] #build#119(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at C:\Users\Erik\.julia\v0.6\JuMP\src\solvers.jl:324
 [8] (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at .\<missing>:0
 [9] #solve#116(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at C:\Users\Erik\.julia\v0.6\JuMP\src\solvers.jl:168
 [10] solve(::JuMP.Model) at C:\Users\Erik\.julia\v0.6\JuMP\src\solvers.jl:150
 [11] include_from_node1 at .\loading.jl:576
 [12] include at .\sysimg.jl:14
 [13] process_options at .\client.jl:305
 [14] _start at .\client.jl:371
```
Please, I need some help.

**Comment by aszekMosek** [comment] 2018-02-07 12:32
Could you send a reproducible code example? 

If you google there are lots of hits for this error in Julia on Windows generally, for instance https://github.com/JuliaOpt/Ipopt.jl/issues/77

**Comment by erikfilias** [comment] 2018-02-07 12:48
**This is an example that I ran with SCS Solver but I couldn't run with Mosek Solver:**

```
using JuMP
using Mosek
#using SCS

model = Model(solver=MosekSolver())
#model = Model(solver=SCSSolver())

@variable(model, Q[1:2, 1:2], SDP)
@constraint(model, Q[1,1] - 1 == Q[2,2])
@variable(model, objective)
T = [1 Q[1,1]; Q[1,1] objective]
@SDconstraint(model, T >= 0)
@objective(model, :Min, objective)
solve(model)

#println("Objective value: ", getobjectivevalue(model))
#println("Q: ", getvalue(Q))

@show getvalue(Q)
@show getobjectivevalue(model)
@show getvalue(objective)
@assert getobjectivevalue(model) == getvalue(objective)
```

And, I get the error:
```
ERROR: LoadError: ReadOnlyMemoryError()
Stacktrace:
 [1] (::Mosek.##375#376{Mosek.Task,Int32,Int32,Array{Int64,1},Array{Float64,1},Int32})() at C:\Users\Erik\.julia\v0.6\Mosek\src\msk_functions.jl:5623
 [2] disable_sigint at .\c.jl:340 [inlined]
 [3] putbaraij(::Mosek.Task, ::Int32, ::Int32, ::Array{Int64,1}, ::Array{Float64,1}) at C:\Users\Erik\.julia\v0.6\Mosek\src\msk_functions.jl:5622
 [4] loadproblem!(::Mosek.MosekMathProgSolverInterface.MosekMathProgConicModel, ::Array{Float64,1}, ::SparseMatrixCSC{Float64,Int32}, ::Array{Float64,1}, ::Array{Tuple{Symbol,Any},1}, ::Array{Tuple{Symbol,Any},1}, ::Symbol) at C:\Users\Erik\.julia\v0.6\Mosek\src\MosekConicInterface.jl:278
 [5] loadproblem!(::Mosek.MosekMathProgSolverInterface.MosekMathProgConicModel, ::Array{Float64,1}, ::SparseMatrixCSC{Float64,Int32}, ::Array{Float64,1}, ::Array{Any,1}, ::Array{Any,1}, ::Symbol) at C:\Users\Erik\.julia\v0.6\Mosek\src\MosekConicInterface.jl:99
 [6] loadproblem!(::Mosek.MosekMathProgSolverInterface.MosekMathProgConicModel, ::Array{Float64,1}, ::SparseMatrixCSC{Float64,Int32}, ::Array{Float64,1}, ::Array{Any,1}, ::Array{Any,1}) at C:\Users\Erik\.julia\v0.6\Mosek\src\MosekConicInterface.jl:88
 [7] #build#119(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::JuMP.Model) at C:\Users\Erik\.julia\v0.6\JuMP\src\solvers.jl:324
 [8] (::JuMP.#kw##build)(::Array{Any,1}, ::JuMP.#build, ::JuMP.Model) at .\<missing>:0
 [9] #solve#116(::Bool, ::Bool, ::Bool, ::Array{Any,1}, ::Function, ::JuMP.Model) at C:\Users\Erik\.julia\v0.6\JuMP\src\solvers.jl:168
 [10] solve(::JuMP.Model) at C:\Users\Erik\.julia\v0.6\JuMP\src\solvers.jl:150
 [11] include_from_node1 at .\loading.jl:576
 [12] include at .\sysimg.jl:14
 [13] process_options at .\client.jl:305
 [14] _start at .\client.jl:371
```

**What kind of problem could I get?**

**Comment by aszekMosek** [comment] 2018-02-07 13:13
Everything OK on linux with Julia 0.6.0. I'll let you know when I have checked with your setup.

**Comment by erikfilias** [comment] 2018-02-07 13:17
@aszekMosek 
Thank you somuch!
I am working in Windows 10 and Julia 0.6.0.
And, the following status:

```
julia> Pkg.status()
11 required packages:
 - Atom                          0.6.9
 - CPLEX                         0.3.1
 - CSDP                          0.0.3
 - Clp                           0.3.1
 - ConditionalJuMP               0.0.3
 - GLPKMathProgInterface         0.3.4
 - Ipopt                         0.2.6
 - JuMP                          0.18.0
 - Mosek                         0.8.2
 - SCIP                          0.5.0
 - SCS                           0.3.3
57 additional packages:
 - ASTInterpreter2               0.1.1
 - AdjacentFloats                0.0.6
 - BinDeps                       0.8.6
 - Blink                         0.6.0
 - BufferedStreams               0.3.3
 - CRlibm                        0.5.0
 - Calculus                      0.2.2
 - Cbc                           0.3.2
 - CodeTools                     0.4.7
 - Codecs                        0.4.0
 - CommonSubexpressions          0.0.1
 - Compat                        0.52.0
 - DataStructures                0.7.4
 - DebuggerFramework             0.1.2
 - DiffResults                   0.0.3
 - DiffRules                     0.0.3
 - Distances                     0.5.0
 - DocSeeker                     0.1.0
 - ErrorfreeArithmetic           0.0.3
 - FastRounding                  0.0.5
 - ForwardDiff                   0.7.3
 - GLPK                          0.5.0
 - GZip                          0.3.0
 - Glob                          1.1.1
 - Hiccup                        0.1.1
 - HttpCommon                    0.4.0
 - HttpParser                    0.3.0
 - HttpServer                    0.3.0
 - IntervalArithmetic            0.11.0
 - IterTools                     0.2.1
 - JSON                          0.16.4
 - Juno                          0.4.0
 - LNR                           0.0.2
 - Lazy                          0.12.0
 - LibExpat                      0.4.1
 - Libz                          0.2.4
 - MacroTools                    0.4.0
 - MathProgBase                  0.6.4
 - MbedTLS                       0.5.5
 - Media                         0.3.0
 - Mustache                      0.3.0
 - Mux                           0.2.3
 - NaNMath                       0.3.1
 - Nullables                     0.0.3
 - RecipesBase                   0.2.3
 - Reexport                      0.1.0
 - Requires                      0.4.3
 - ReverseDiffSparse             0.8.1
 - SHA                           0.5.6
 - SemidefiniteModels            0.0.3
 - SpecialFunctions              0.3.8
 - StaticArrays                  0.6.6
 - StringDistances               0.2.0
 - Tokenize                      0.4.2
 - URIParser                     0.3.0
 - WebSockets                    0.4.0
 - WinRPM                        0.3.1
```

**Comment by aszekMosek** [comment] 2018-02-08 09:26
I cannot reproduce it. Everything works. I will ask the author @ulfworsoe to look at this, but he is not available for a while.

The only thing I can suggest is download the Mosek Windows installer from our website and run it. This will install a C++ redistributable library, maybe that will help.

**Comment by erikfilias** [comment] 2018-02-12 12:21
@aszekMosek , I downloaded and installed the Mosek Windows. In addition, I reinstalled JuliaLang with all packages again. And, the Mosek works well. I think there was anything that generates a conflict with Mosek but It works great now. Thank you so much.

**Comment by ulfworsoe** [comment] 2018-02-19 10:59
I have not been able to reproduce the problem with a Julia 0.6.2 and a fresh install, so I'll close the issue. I am not sure what might cause the problem, but we *do* depend some third-party libraries that might be shared with other applications (MS and Intel redistributables).

**Closed by ulfworsoe** 2018-02-19 10:59 UTC
