### ISSUE TITLE
OPTIMIZER_MAX_TIME ignored

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Mosek.jl#42] opened 2015-04-14 22:42 UTC
Reported by @mgoycool and @juan-pablo-vielma. When setting the ``OPTIMIZER_MAX_TIME`` through ``MosekSolver(OPTIMIZER_MAX_TIME=1.0)``, the parameter seems to be ignored.
Some debugging steps:
```
getnadouparam(m.task, "MSK_DPAR_OPTIMIZER_MAX_TIME")
```
returns the *correct* value.

If the parameter is set with:
```
putdouparam(m.task, MSK_DPAR_OPTIMIZER_MAX_TIME, 1.0)
```
instead of (via [this line](https://github.com/JuliaOpt/Mosek.jl/blob/7e4916ed43e16c8778cc522d7d81ac9c2de10d5e/src/MosekSolverInterface.jl#L117)),
```
putnadouparam(m.task, "MSK_DPAR_OPTIMIZER_MAX_TIME", 1.0)
```
then everything works fine. So something nontrivial seems to be wrong in ``putnadouparam``.

**Comment by juan-pablo-vielma** [comment] 2015-04-14 23:00
An interesting detail for the conic interior point solver: if the time limit is reached in pre-solve it is respected, but if it is reached in the main iteration it is ignored.

**Comment by ulfworsoe** [comment] 2015-04-15 06:28
The set/getnadouparam: I can't reproduce it with the current master and MOSEK 7.1. Both `putnadouparam` and `putdouparam` appear to set the parameter.

 Time limit not respected: That must be a solver issue. I'll pass it on to the interior-point guy.

**Comment by ulfworsoe** [comment] 2016-06-08 09:32
This appears to work now. Closing.

**Closed by ulfworsoe** 2016-06-08 09:32 UTC
