### ISSUE TITLE
Mosek.jl 0.1.4 fails to build on OS X 

### ISSUE THREAD

**Issue by xiaoweiz** [JuliaOpt/Mosek.jl#35] opened 2015-02-26 12:48 UTC
I'm running Julia 0.3.5 on OS X Yosemite. `Mosek.jl` _was_ installed before and worked without problem. I run `Pkg.update()` earlier today and it tried to update `Mosek.jl` to version 0.1.4. However, I received the following building error

```shell
================================[ ERROR: Mosek ]================================

None of the selected providers can install dependency libmosek.
Use BinDeps.debug(package_name) to see available providers

while loading /Users/xiaoweiz/.julia/v0.3/Mosek/deps/build.jl, in expression starting on line 87

================================================================================

================================[ BUILD ERRORS ]================================

WARNING: Mosek had build errors.

 - packages with build errors remain installed in /Users/xiaoweiz/.julia/v0.3
 - build the package(s) and all dependencies with `Pkg.build("Mosek")`
 - build a single package by running its `deps/build.jl` script

===============================================================================
```

Then running `BinDeps.debug("Mosek")` gives 
```shell
The package declares 2 dependencies.
 - Library "libmosek"
    - Providers:
      - Binaries (can't provide)
 - Library "libmosekscopt"
```

However, on another machine with Ubuntu 14.04, `Mosek.jl` was indeed successfully updated to 0.1.4.

**Comment by ulfworsoe** [comment] 2015-02-26 14:02
I'll take a look at it as soon as possible. 

Did you install Mosek.jl using a pre-installed MOSEK distro or did the installer download the binary MOSEK package?

**Comment by xiaoweiz** [comment] 2015-02-26 14:18
Thanks for the quick response.

What do you mean by MOSEK distro? I downloaded the Mosek package from [MOSEK's official website](https://mosek.com/resources/downloads)

**Comment by ulfworsoe** [comment] 2015-02-26 15:12
Ok, that is actually what I wanted to know. Mosek.jl can install itself in two ways when you do `Pkg.add("Mosek")`. First it will look i the default installation path for a pre-existing MOSEK installation; if it finds one, it will use that. Otherwise, it will attempt to download and unpack the MOSEK distro directly. 

I will try to fix this as soon as I get access to an OS X machine.

**Comment by mlubin** [comment] 2015-02-26 15:16
@xiaoweiz, what is the installation path of Mosek on your computer? I.e., which directory has a file called ``libmosek64.7.0.dylib``?

**Comment by xiaoweiz** [comment] 2015-02-26 15:24
It's in the home directory `/Users/xiaoweiz/mosek/7/tools/platform/osx64x86/bin/libmosekglb64.7.1.dylib`

**Comment by mlubin** [comment] 2015-02-26 15:27
Possibly a duplicate of #21, see the workaround there.

**Comment by mlubin** [comment] 2015-02-26 15:34
@ulfworsoe, at this point I'd recommend rewriting ``build.jl`` to not use BinDeps at all. It seems to be a continuing source of problems.

**Comment by juan-pablo-vielma** [comment] 2015-04-07 17:29
It seems the error is because a missing 
`provides(Binaries, ENV["MOSEKBINDIR"], libmosekscopt)`
when using MOSEKBINDIR

Changing

 ```
if haskey(ENV,"MOSEKBINDIR")
provides(Binaries, ENV["MOSEKBINDIR"], libmosek)
# 2a. Otherwise, use the default installation path (Linux)
```

to 
```
if haskey(ENV,"MOSEKBINDIR")
  provides(Binaries, ENV["MOSEKBINDIR"], libmosek)
  provides(Binaries, ENV["MOSEKBINDIR"], libmosekscopt)
# 2a. Otherwise, use the default installation path (Linux)
```
in `build.jl` resolved it for me

**Comment by joehuchette** [comment] 2015-04-07 17:36
I believe that change is already [on master](https://github.com/JuliaOpt/Mosek.jl/blob/12481bfb87b4e9124e8c87cd7a7dc7882305d698/deps/build.jl#L40-L42)

**Comment by ulfworsoe** [comment] 2015-04-08 08:56
I will take a look at rewriting the library stuff without BinDeps as soon as possible.

**Comment by ulfworsoe** [comment] 2015-04-13 09:03
This should work now. See issue #41 .

**Closed by ulfworsoe** 2015-04-13 09:03 UTC
